CREATE TABLE IF NOT EXISTS products (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL DEFAULT 'Other',
  price_per_unit NUMERIC(12, 2) NOT NULL,
  unit TEXT NOT NULL DEFAULT 'L',
  purchase_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
  stock INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS customers (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  card_number TEXT NOT NULL UNIQUE,
  barcode TEXT UNIQUE,
  mobile TEXT NOT NULL,
  points INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS redeemable_products (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  points_required INTEGER NOT NULL,
  stock INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS sales (
  id SERIAL PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  customer_id INTEGER REFERENCES customers(id) ON DELETE SET NULL,
  units INTEGER NOT NULL,
  amount NUMERIC(12, 2) NOT NULL,
  purchase_cost NUMERIC(12, 2) NOT NULL,
  profit NUMERIC(12, 2) NOT NULL,
  points_earned INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS redemptions (
  id SERIAL PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  points_spent INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS redemption_items (
  id SERIAL PRIMARY KEY,
  redemption_id INTEGER NOT NULL REFERENCES redemptions(id) ON DELETE CASCADE,
  redeemable_product_id INTEGER NOT NULL REFERENCES redeemable_products(id) ON DELETE RESTRICT,
  quantity INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS push_notifications (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS auth_config (
  id SERIAL PRIMARY KEY,
  email TEXT,
  password_salt TEXT,
  password_hash TEXT,
  pin_salt TEXT,
  pin_hash TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE auth_config
  ADD COLUMN IF NOT EXISTS email TEXT;

ALTER TABLE auth_config
  ADD COLUMN IF NOT EXISTS password_salt TEXT;

ALTER TABLE auth_config
  ADD COLUMN IF NOT EXISTS password_hash TEXT;

ALTER TABLE auth_config
  ALTER COLUMN pin_salt DROP NOT NULL;

ALTER TABLE auth_config
  ALTER COLUMN pin_hash DROP NOT NULL;

CREATE TABLE IF NOT EXISTS auth_sessions (
  token TEXT PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS auth_users (
  id SERIAL PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_salt TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE auth_sessions
  ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES auth_users(id) ON DELETE CASCADE;
